# syntax=docker/dockerfile:1

############################
# Builder
############################
FROM rockylinux:9 AS builder
WORKDIR /build

# ---- 构建依赖 ----
RUN dnf -y update && \
    dnf install -y dnf-plugins-core && \
    dnf config-manager --set-enabled crb && \
    dnf install -y \
        gcc gcc-c++ make binutils \
        clang \
        cmake \
        pkg-config \
        git curl \
        protobuf-devel protobuf-compiler \
        sqlite-devel \
        librdkafka-devel \
        zlib-devel \
        openssl-devel \
        ca-certificates && \
    dnf clean all

# ---- Rust ----
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup default stable

# ---- FoundationDB client ----
ARG TARGETARCH
COPY resources/libfdb_c.${TARGETARCH}.so /usr/lib64/libfdb_c.so
RUN chmod 755 /usr/lib64/libfdb_c.so && ldconfig

# ---- Build ----
COPY . .

RUN cargo build --release \
    -p stalwart \
    --manifest-path crates/main/Cargo.toml \
    --no-default-features \
    --features "sqlite foundationdb kafka enterprise"

RUN cargo build --release \
    -p stalwart-cli \
    --no-default-features \
    --features "sqlite foundationdb kafka enterprise"

RUN mkdir -p /output && \
    cp target/release/stalwart /output/ && \
    cp target/release/stalwart-cli /output/


############################
# Runtime
############################
FROM rockylinux:9
WORKDIR /opt/stalwart

# ---- 运行时依赖 ----
RUN dnf -y update && \
    dnf install -y \
        ca-certificates \
        librdkafka \
        zlib \
        openssl && \
    dnf clean all

# ---- FoundationDB client ----
ARG TARGETARCH
COPY resources/libfdb_c.${TARGETARCH}.so /usr/lib64/libfdb_c.so
RUN chmod 755 /usr/lib64/libfdb_c.so && ldconfig

# ---- App ----
COPY --from=builder /output/stalwart /usr/local/bin/stalwart
COPY --from=builder /output/stalwart-cli /usr/local/bin/stalwart-cli
COPY resources/docker/entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod 755 \
    /usr/local/bin/stalwart \
    /usr/local/bin/stalwart-cli \
    /usr/local/bin/entrypoint.sh

VOLUME ["/opt/stalwart"]

EXPOSE 443 25 110 587 465 143 993 995 4190 8080

ENTRYPOINT ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
CMD ["/usr/local/bin/stalwart"]