# syntax=docker/dockerfile:1
FROM rockylinux:9.6 AS builder
WORKDIR /build

# 安装构建依赖和 rust
RUN dnf update -y && \
    dnf install -y clang gcc make binutils curl git protobuf-devel sqlite-devel protobuf-compiler && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    . $HOME/.cargo/env && rustup default stable

COPY resources/libfdb_c.so /lib64/
RUN chmod 755 /lib64/libfdb_c.so

COPY . .
RUN . $HOME/.cargo/env && cargo build --release -p stalwart --manifest-path=crates/main/Cargo.toml --no-default-features --features "sqlite postgres mysql rocks elastic s3 redis azure nats enterprise"
RUN . $HOME/.cargo/env && cargo build --release -p stalwart-cli
RUN mkdir /output && cp target/release/stalwart /output/ && cp target/release/stalwart-cli /output/

FROM registry.access.redhat.com/ubi9/ubi:9.6-1749542372
WORKDIR /opt/stalwart
RUN dnf update -y && dnf install -y ca-certificates && dnf clean all
COPY --from=builder /output/stalwart /usr/local/bin
COPY --from=builder /output/stalwart-cli /usr/local/bin
COPY ./resources/docker/entrypoint.sh /usr/local/bin/entrypoint.sh
COPY resources/libfdb_c.so /lib64/
RUN chmod -R 755 /usr/local/bin && ldconfig
CMD ["/usr/local/bin/stalwart"]
VOLUME [ "/opt/stalwart" ]
EXPOSE 443 25 110 587 465 143 993 995 4190 8080
ENTRYPOINT ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
