name: Build and Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: Clone stalwart repository
      run: |
        git clone https://github.com/offsoc/stalwart.git
        cd stalwart

    - name: Install Rust manually
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        wget https://github.com/apple/foundationdb/releases/download/7.3.67/foundationdb-clients_7.3.67-1_amd64.deb
        sudo dpkg -i foundationdb-clients_7.3.67-1_amd64.deb || true

    - name: Build
      run: cargo build --manifest-path=stalwart/crates/main/Cargo.toml --release

    - name: Upload stalwart binary
      uses: actions/upload-artifact@v3
      with:
        name: stalwart
        path: stalwart/target/release/stalwart*
