name: Rust Security CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '00 12 * * *'

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # Run cargo audit
      - name: Run cargo audit
        run: |
          cargo install cargo-audit
          cargo audit --deny=warnings

      # Run Clippy for static analysis
      - name: Run Clippy
        run: cargo clippy -- -D warnings

      # Run rustsec to check vulnerabilities in dependencies
      - name: Run rustsec check
        run: cargo install rustsec && rustsec advisory --workspace

      # Build Docker image and scan it with Trivy
      - name: Set up Trivy
        uses: aquasecurity/trivy-action@master
      
        with:
          scan-type: 'image'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy image scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-results.sarif'
